# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        environment:
          FLASK_CONFIG: testing
      - image: cimg/node:18.16.1
      - image: cimg/firefox:latest

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "config/requirements-dev.txt" }}
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
      # Install Python dependencies
      - run:
          name: install python deps
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r config/requirements-dev.txt
      # Save Python dependencies to cache
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "config/requirements-dev.txt" }}
          paths:
            - "env"
      # NPM INSTALL
      - run:
          name: install npm deps
          command: |
            npm install
      # Save NPM dependencies to cache
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
      # Verify Firefox installation
      - run:
          name: Verify Firefox installation
          command: |
            firefox --version
            which firefox
      # Run tests
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            NODE_OPTIONS=--max_old_space_size=8192
            npm run lint
            npm run build
            pip install -e .
            pytest tests
            npm run test:unit-js
            python run.py -t &
            sleep 5
            npx intern
      # Store test reports
      - store_artifacts:
          path: test-reports/
          destination: test-reports
