# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/python:3.9.1-browsers
        environment:
          FLASK_CONFIG: testing

    working_directory: ~/repo

    steps:
      - checkout
      - browser-tools/install-browser-tools
      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps1.1-{{ .Branch }}-{{ checksum "config/requirements-dev.txt" }}
      - run:
          name: install python deps
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r config/requirements-dev.txt
      - save_cache:
          key: deps1.1-{{ .Branch }}-{{ checksum "config/requirements-dev.txt" }}
          paths:
            - "env"
      # NPM INSTALL
      - run:
          name: install npm deps
          command: |
            npm install

      # Verify Firefox installation
      - run:
          name: Verify Firefox installation
          command: |
            firefox --version
            which firefox

      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            NODE_OPTIONS=--max_old_space_size=8192
            npm run lint
            npm run build
            pip install -e .
            pytest tests
            npm run test:unit-js
            python run.py -t &
            sleep 5
            npx intern
      - store_artifacts:
          path: test-reports/
          destination: test-reports
